import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const sampleProducts = [
  {
    name: "Thịt Heo Nạc Tươi",
    slug: "thit-heo-nac-tuoi",
    description: "Thịt heo nạc tươi ngon, được chọn lọc từ những con heo khỏe mạnh, đảm bảo chất lượng và an toàn thực phẩm.",
    price: 89000,
    originalPrice: 120000,
    discount: 26,
    image: "/fresh-lean-pork-meat.jpg",
    category: "thit-heo",
    subcategory: "thit-nac",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 50,
    minStock: 10,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["tươi ngon", "chất lượng cao", "an toàn"]),
    nutrition: JSON.stringify({
      calories: 250,
      protein: 26,
      fat: 15,
      carbs: 0,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 3
  },
  {
    name: "Thịt Heo Ba Chỉ",
    slug: "thit-heo-ba-chi",
    description: "Thịt heo ba chỉ với lớp mỡ vừa phải, thịt mềm ngọt, thích hợp cho các món nướng và chiên.",
    price: 95000,
    originalPrice: 130000,
    discount: 27,
    image: "/pork-belly-meat.jpg",
    category: "thit-heo",
    subcategory: "thit-ba-chi",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 30,
    minStock: 8,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: JSON.stringify(["ba chỉ", "nướng", "chiên"]),
    nutrition: JSON.stringify({
      calories: 320,
      protein: 20,
      fat: 25,
      carbs: 0,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 3
  },
  {
    name: "Thịt Heo Sườn",
    slug: "thit-heo-suon",
    description: "Sườn heo tươi ngon, thịt mềm và ngọt, thích hợp cho các món nướng và kho.",
    price: 105000,
    originalPrice: 145000,
    discount: 28,
    image: "/pork-ribs-fresh.jpg",
    category: "thit-heo",
    subcategory: "suon",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 25,
    minStock: 5,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: JSON.stringify(["sườn", "nướng", "kho"]),
    nutrition: JSON.stringify({
      calories: 280,
      protein: 22,
      fat: 20,
      carbs: 0,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 3
  },
  {
    name: "Thịt Bò Tươi",
    slug: "thit-bo-tuoi",
    description: "Thịt bò tươi ngon, được nhập khẩu từ Úc, đảm bảo chất lượng cao và an toàn thực phẩm.",
    price: 150000,
    originalPrice: 200000,
    discount: 25,
    image: "/fresh-beef-meat.jpg",
    category: "thit-bo",
    subcategory: "thit-nac-bo",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 20,
    minStock: 5,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["thịt bò", "nhập khẩu", "chất lượng cao"]),
    nutrition: JSON.stringify({
      calories: 200,
      protein: 30,
      fat: 10,
      carbs: 0,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 5
  },
  {
    name: "Combo Thịt Healthy",
    slug: "combo-thit-healthy",
    description: "Combo thịt healthy bao gồm thịt heo nạc, thịt bò và thịt gà, đảm bảo dinh dưỡng cân bằng.",
    price: 159000,
    originalPrice: 227000,
    discount: 30,
    image: "/healthy-meat-combo.jpg",
    category: "combo",
    subcategory: "combo-healthy",
    brand: "Mẹ Phương",
    weight: 1000,
    unit: "g",
    stock: 15,
    minStock: 3,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["combo", "healthy", "đa dạng"]),
    nutrition: JSON.stringify({
      calories: 250,
      protein: 28,
      fat: 12,
      carbs: 2,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 3
  },
  {
    name: "Thịt Heo Xay",
    slug: "thit-heo-xay",
    description: "Thịt heo xay tươi ngon, thích hợp cho các món chả, nem và các món ăn gia đình.",
    price: 75000,
    originalPrice: 110000,
    discount: 32,
    image: "/ground-pork-meat.jpg",
    category: "thit-heo",
    subcategory: "thit-xay",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 40,
    minStock: 10,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: JSON.stringify(["thịt xay", "chả", "nem"]),
    nutrition: JSON.stringify({
      calories: 300,
      protein: 25,
      fat: 22,
      carbs: 0,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 2
  },
  {
    name: "Thịt Heo Chân",
    slug: "thit-heo-chan",
    description: "Thịt heo chân tươi ngon, thích hợp cho các món hầm và nấu canh.",
    price: 45000,
    originalPrice: 60000,
    discount: 25,
    image: "/pork-leg-meat.jpg",
    category: "thit-heo",
    subcategory: "thit-chan",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 35,
    minStock: 8,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: JSON.stringify(["thịt chân", "hầm", "canh"]),
    nutrition: JSON.stringify({
      calories: 180,
      protein: 20,
      fat: 10,
      carbs: 0,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 3
  },
  {
    name: "Thịt Heo Cốt Lết",
    slug: "thit-heo-cot-let",
    description: "Thịt heo cốt lết premium, thịt mềm và ngọt, thích hợp cho các món nướng và chiên.",
    price: 125000,
    originalPrice: 170000,
    discount: 26,
    image: "/pork-chops-premium.jpg",
    category: "thit-heo",
    subcategory: "cot-let",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 18,
    minStock: 5,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["cốt lết", "premium", "nướng"]),
    nutrition: JSON.stringify({
      calories: 290,
      protein: 24,
      fat: 20,
      carbs: 0,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh ở nhiệt độ 0-4°C",
    expiry: 3
  },
  // Sản phẩm chế biến
  {
    name: "Giăm Bông Thơm",
    slug: "giam-bong-thom",
    description: "Giăm bông thơm ngon, được chế biến từ thịt heo tươi ngon. Có vị thơm đặc trưng, mềm mại, phù hợp cho các món ăn sáng, bánh mì, salad.",
    price: 89000,
    originalPrice: 120000,
    discount: 26,
    image: "/processed-ham-meat.jpg",
    category: "Thịt chế biến",
    subcategory: "Giăm bông",
    brand: "Mẹ Phương",
    weight: 1000,
    unit: "g",
    stock: 50,
    minStock: 10,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["Thơm ngon", "Chế biến", "Tiện lợi", "Chất lượng cao"]),
    nutrition: JSON.stringify({
      calories: 280,
      protein: 22,
      fat: 20,
      carbs: 2,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 7
  },
  {
    name: "Xúc Xích Thịt Heo",
    slug: "xuc-xich-thit-heo",
    description: "Xúc xích thịt heo tươi ngon, được chế biến từ thịt heo chất lượng cao. Có vị thơm ngon, mềm mại, phù hợp cho các món nướng, chiên, luộc.",
    price: 65000,
    originalPrice: 85000,
    discount: 24,
    image: "/pork-sausage-product.jpg",
    category: "Thịt chế biến",
    subcategory: "Xúc xích",
    brand: "Mẹ Phương",
    weight: 1000,
    unit: "g",
    stock: 30,
    minStock: 8,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: JSON.stringify(["Thơm ngon", "Chế biến", "Tiện lợi", "Đa dụng"]),
    nutrition: JSON.stringify({
      calories: 320,
      protein: 18,
      fat: 25,
      carbs: 3,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 5
  },
  {
    name: "Thịt Xông Khói",
    slug: "thit-xong-khoi",
    description: "Thịt xông khói thơm ngon, được xông khói tự nhiên. Có vị thơm đặc trưng, mềm mại, phù hợp cho các món ăn sáng, bánh mì, salad.",
    price: 95000,
    originalPrice: 130000,
    discount: 27,
    image: "/smoked-pork-meat.jpg",
    category: "Thịt chế biến",
    subcategory: "Xông khói",
    brand: "Mẹ Phương",
    weight: 1000,
    unit: "g",
    stock: 25,
    minStock: 5,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["Thơm ngon", "Xông khói", "Đặc biệt", "Premium"]),
    nutrition: JSON.stringify({
      calories: 350,
      protein: 20,
      fat: 28,
      carbs: 1,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 10
  },
  {
    name: "Chả Lụa Thịt Heo",
    slug: "cha-lua-thit-heo",
    description: "Chả lụa thịt heo tươi ngon, được chế biến từ thịt heo chất lượng cao. Có vị thơm ngon, mềm mại, phù hợp cho các món ăn sáng, bánh mì.",
    price: 55000,
    originalPrice: 75000,
    discount: 27,
    image: "/pork-pate-product.jpg",
    category: "Thịt chế biến",
    subcategory: "Chả lụa",
    brand: "Mẹ Phương",
    weight: 1000,
    unit: "g",
    stock: 40,
    minStock: 8,
    isActive: true,
    isFeatured: false,
    isFlashSale: false,
    tags: JSON.stringify(["Thơm ngon", "Chế biến", "Truyền thống", "Chất lượng cao"]),
    nutrition: JSON.stringify({
      calories: 280,
      protein: 25,
      fat: 18,
      carbs: 2,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 6
  },
  {
    name: "Thịt Hộp Đóng Hộp",
    slug: "thit-hop-dong-hop",
    description: "Thịt heo đóng hộp tiện lợi, bảo quản lâu dài. Thịt mềm ngon, có thể sử dụng trực tiếp hoặc chế biến thành các món ăn khác.",
    price: 45000,
    originalPrice: 60000,
    discount: 25,
    image: "/canned-pork-meat.jpg",
    category: "Thịt chế biến",
    subcategory: "Đóng hộp",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 60,
    minStock: 15,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: JSON.stringify(["Tiện lợi", "Đóng hộp", "Bảo quản lâu", "Chất lượng cao"]),
    nutrition: JSON.stringify({
      calories: 250,
      protein: 20,
      fat: 15,
      carbs: 5,
      fiber: 0
    }),
    storage: "Bảo quản nơi khô ráo, thoáng mát",
    expiry: 365
  },
  {
    name: "Xúc Xích Nướng",
    slug: "xuc-xich-nuong",
    description: "Xúc xích nướng thơm ngon, được chế biến đặc biệt cho món nướng. Có vị đậm đà, thơm ngon, phù hợp cho các bữa tiệc nướng.",
    price: 72000,
    originalPrice: 95000,
    discount: 24,
    image: "/grilled-sausage-product.jpg",
    category: "Thịt chế biến",
    subcategory: "Xúc xích",
    brand: "Mẹ Phương",
    weight: 1000,
    unit: "g",
    stock: 35,
    minStock: 8,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["Thơm ngon", "Nướng", "Tiệc tùng", "Đặc biệt"]),
    nutrition: JSON.stringify({
      calories: 340,
      protein: 19,
      fat: 26,
      carbs: 4,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 5
  },
  {
    name: "Thịt Gác Bếp",
    slug: "thit-gac-bep",
    description: "Thịt gác bếp truyền thống, được chế biến theo phương pháp cổ truyền. Thịt có vị đậm đà, thơm ngon đặc trưng, phù hợp cho các món ăn truyền thống.",
    price: 120000,
    originalPrice: 160000,
    discount: 25,
    image: "/cured-pork-meat.jpg",
    category: "Thịt chế biến",
    subcategory: "Gác bếp",
    brand: "Mẹ Phương",
    weight: 1000,
    unit: "g",
    stock: 20,
    minStock: 3,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["Truyền thống", "Gác bếp", "Đặc biệt", "Premium"]),
    nutrition: JSON.stringify({
      calories: 380,
      protein: 25,
      fat: 30,
      carbs: 2,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 15
  },
  {
    name: "Chả Chiên Thịt Heo",
    slug: "cha-chien-thit-heo",
    description: "Chả chiên thịt heo giòn ngon, được chế biến từ thịt heo tươi ngon. Có lớp vỏ giòn, nhân thịt mềm ngon, phù hợp cho các món ăn sáng.",
    price: 48000,
    originalPrice: 65000,
    discount: 26,
    image: "/fried-pork-cake.jpg",
    category: "Thịt chế biến",
    subcategory: "Chả chiên",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 45,
    minStock: 10,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: JSON.stringify(["Giòn ngon", "Chiên", "Tiện lợi", "Chất lượng cao"]),
    nutrition: JSON.stringify({
      calories: 300,
      protein: 18,
      fat: 22,
      carbs: 8,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 4
  },
  {
    name: "Thịt Chà Bông Heo",
    slug: "thit-cha-bong-heo",
    description: "Thịt chà bông heo truyền thống, được sấy khô cẩn thận. Có vị đậm đà, thơm ngon, phù hợp cho các món ăn sáng, cháo, cơm chiên.",
    price: 85000,
    originalPrice: 110000,
    discount: 23,
    image: "/cured-pork-meat.jpg",
    category: "Thịt chế biến",
    subcategory: "Chà bông",
    brand: "Mẹ Phương",
    weight: 500,
    unit: "g",
    stock: 35,
    minStock: 8,
    isActive: true,
    isFeatured: false,
    isFlashSale: true,
    tags: JSON.stringify(["Chà bông", "Truyền thống", "Thơm ngon", "Đậm đà"]),
    nutrition: JSON.stringify({
      calories: 450,
      protein: 35,
      fat: 30,
      carbs: 5,
      fiber: 0
    }),
    storage: "Bảo quản nơi khô ráo, thoáng mát",
    expiry: 30
  },
  {
    name: "Pate Gan Heo",
    slug: "pate-gan-heo",
    description: "Pate gan heo thơm ngon, mềm mịn. Phù hợp cho bánh mì, sandwich, và các món ăn sáng.",
    price: 52000,
    originalPrice: 70000,
    discount: 26,
    image: "/pork-pate-product.jpg",
    category: "Thịt chế biến",
    subcategory: "Pate",
    brand: "Mẹ Phương",
    weight: 250,
    unit: "g",
    stock: 50,
    minStock: 10,
    isActive: true,
    isFeatured: true,
    isFlashSale: false,
    tags: JSON.stringify(["Pate", "Gan heo", "Thơm ngon", "Tiện lợi"]),
    nutrition: JSON.stringify({
      calories: 320,
      protein: 15,
      fat: 28,
      carbs: 3,
      fiber: 0
    }),
    storage: "Bảo quản trong tủ lạnh 0-4°C",
    expiry: 14
  }
]


async function main() {
  console.log('🌱 Bắt đầu seed dữ liệu...')

  try {
    // Create products
    console.log('🛍️ Tạo sản phẩm...')
    for (const productData of sampleProducts) {
      await prisma.product.upsert({
        where: { slug: productData.slug },
        update: productData,
        create: productData
      })
    }

    console.log('✅ Seed dữ liệu thành công!')
    console.log(`📊 Đã tạo ${sampleProducts.length} sản phẩm`)

  } catch (error) {
    console.error('❌ Lỗi khi seed dữ liệu:', error)
  } finally {
    await prisma.$disconnect()
  }
}

main()
  .catch((e: unknown) => {
    console.error(e)
    process.exit(1)
  })
